"""
analysis/reports/markdown_report.py
=====================================
Render a markdown report from one or more normalised run summaries.

The report is structured as:

1. Header + run metadata table
2. DL coverage diagnostics (if present)
3. Walkforward OOS performance (Sharpe / return / DD / fold stability)
4. Selector uplift (baseline vs dynamic)
5. Ablation summary
6. Vol guard diagnostics
7. Backtest / in-sample ML accuracy (legacy / fallback)
8. Comparison section (sentiment ON/OFF, Gen1 vs Gen2)
9. Warnings and missing sections

Each section degrades gracefully: if the underlying data is absent, the
section header still appears with a ``⚠ Data not available`` note.
"""

from __future__ import annotations

from typing import Any


def render_markdown_report(
    summaries: list[dict[str, Any]],
    comparisons: dict[str, Any] | None = None,
    *,
    validation: dict[str, Any] | None = None,
) -> str:
    """
    Build a markdown string from *summaries* and optional *comparisons*.

    Parameters
    ----------
    summaries:
        List of normalised run summary dicts (from
        ``analysis.pipeline.build_run_summary``).
    comparisons:
        Optional dict with keys ``sentiment``, ``selector``, ``gen``.

    Returns
    -------
    str
        Markdown text ready to write to ``report.md``.
    """
    lines: list[str] = []
    lines.append("# MPML Experiment Report\n")
    lines.append(
        "> Generated by `analysis/pipeline.py` — analysis framework v2.\n"
    )
    lines.append(
        "> Integrity-first mode: canonical run identities, semantic attribution, and structural validation enabled.\n"
    )

    # ------------------------------------------------------------------
    # 0. Validation / trustworthiness section
    # ------------------------------------------------------------------
    lines.append("## Validation Summary\n")
    if validation:
        errors = validation.get("errors") or []
        warnings = validation.get("warnings") or []
        diagnostics = validation.get("diagnostics") or []
        sections = validation.get("sections") or {}
        lines.append(f"- **Errors:** {len(errors)}")
        lines.append(f"- **Warnings:** {len(warnings)}")
        if diagnostics:
            lines.append(f"- **Diagnostics:** {', '.join(diagnostics)}")
        lines.append("")
        _render_integrity_section(lines, "Provenance Integrity", sections.get("provenance_integrity"))
        _render_integrity_section(lines, "Semantic Integrity", sections.get("semantic_integrity"))
        _render_integrity_section(lines, "Manifest Integrity", sections.get("manifest_integrity"))
        _render_integrity_section(lines, "Reproducibility Integrity", sections.get("reproducibility_integrity"))
        if errors:
            lines.append("\n### ❌ Structural Errors\n")
            for err in errors:
                lines.append(f"- {err}")
        if warnings:
            lines.append("\n### ⚠ Structural Warnings\n")
            for w in warnings:
                lines.append(f"- {w}")
    else:
        lines.append("⚠ No validation payload was provided.")
    lines.append("")

    # ------------------------------------------------------------------
    # 1. Run metadata overview
    # ------------------------------------------------------------------
    lines.append("## Run Overview\n")
    lines.append("| Canonical Run ID | Semantic Run | Meaning | DL Enabled | Gen | Variant | Archive Path | Git SHA | Timestamp UTC |")
    lines.append("|------------------|--------------|---------|-----------|-----|---------|--------------|---------|---------------|")
    for s in summaries:
        meta = s.get("meta") or {}
        lines.append(
            f"| {s.get('run_id', '—')} "
            f"| {meta.get('semantic_run_name', '—')} "
            f"| {meta.get('run_meaning', '—')} "
            f"| {'✓' if meta.get('dl_enabled') else '✗'} "
            f"| {meta.get('experiment_gen', '—')} "
            f"| {meta.get('run_variant', '—')} "
            f"| {meta.get('archive_relpath', '—')} "
            f"| {(meta.get('git_sha') or '—')[:8]} "
            f"| {meta.get('timestamp_utc', '—')} |"
        )
    lines.append("")
    lines.append("### Experiment Semantics Reference\n")
    lines.append("| Run | Meaning |")
    lines.append("|-----|---------|")
    lines.append("| Gen1_A | sentiment ON + missing indicators OFF |")
    lines.append("| Gen1_B | sentiment OFF + missing indicators OFF |")
    lines.append("| Gen2_C | sentiment ON + missing indicators ON |")
    lines.append("| Gen2_D | sentiment OFF + missing indicators ON |")
    lines.append("")

    # ------------------------------------------------------------------
    # Per-run sections
    # ------------------------------------------------------------------
    for summary in summaries:
        run_id = summary.get("run_id", "unknown")
        lines.append(f"---\n\n## Run: `{run_id}`\n")

        _render_warnings_inline(lines, summary.get("warnings") or [])
        _render_manifest_metadata(lines, summary)
        _render_parser_diagnostics(lines, summary)
        _render_dl_coverage(lines, summary)
        _render_walkforward(lines, summary)
        _render_selector_uplift_per_run(lines, summary)
        _render_ablation(lines, summary)
        _render_vol_guard(lines, summary)
        _render_backtest(lines, summary)
        _render_ml_accuracy(lines, summary)

    # ------------------------------------------------------------------
    # Cross-run comparisons
    # ------------------------------------------------------------------
    if comparisons:
        lines.append("---\n\n## Cross-Run Comparisons\n")
        _render_sentiment_comparison(lines, comparisons.get("sentiment"))
        _render_gen_comparison(lines, comparisons.get("gen"))
        _render_selector_aggregate(lines, comparisons.get("selector"))

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------


def _render_warnings_inline(lines: list[str], warnings: list[str]) -> None:
    if warnings:
        lines.append("### ⚠ Warnings\n")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")


def _render_dl_coverage(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### DL Coverage\n")
    csvs = summary.get("csvs") or {}
    log = summary.get("log") or {}

    # Try CSV-based vol_guard_summary first (newer runs)
    vg_rows = csvs.get("vol_guard_summary") or []
    # Fall back to log-parsed dl_coverage
    dl_cov_log = log.get("dl_coverage") or {}

    if vg_rows:
        _table_from_rows(lines, vg_rows, exclude={"_mode_tag"})
    elif dl_cov_log:
        lines.append("| Pair | DL Coverage (%) |")
        lines.append("|------|----------------|")
        for pair, pct in sorted(dl_cov_log.items()):
            lines.append(f"| {pair} | {pct:.2f} |")
    else:
        lines.append("⚠ DL coverage data not available.")
    lines.append("")
    overlap = (summary.get("coverage") or {}).get("overlap_window") or {}
    if overlap:
        lines.append("#### Overlap-Window Diagnostics (Scaffold)\n")
        lines.append(f"- Fold rows present: {overlap.get('fold_rows_present', 0)}")
        lines.append(f"- DL-active years: {', '.join(overlap.get('dl_active_years') or []) or '—'}")
        lines.append(f"- Overlap fold coverage (%): {overlap.get('overlap_fold_coverage_pct', '—')}")
        if overlap.get("per_year_fold_counts"):
            lines.append("| Year | Fold Rows |")
            lines.append("|------|-----------|")
            for year, count in sorted((overlap.get("per_year_fold_counts") or {}).items()):
                lines.append(f"| {year} | {count} |")
        lines.append("")


def _render_walkforward(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Walkforward OOS Performance\n")
    csvs = summary.get("csvs") or {}
    rows = csvs.get("walkforward_summary") or csvs.get("walkforward_per_pair") or []
    if rows:
        wanted = ["Pair", "pair", "Sharpe_Dynamic", "Sharpe_Baseline", "Sharpe_Delta",
                  "Return_Delta", "MaxDD_Delta", "N_Folds"]
        _table_from_rows(lines, rows, include=wanted, exclude={"_mode_tag"})
    else:
        lines.append("⚠ Walkforward data not available.")
    lines.append("")

    # Fold stability (per-fold std / count)
    fold_rows = csvs.get("walkforward_per_fold") or []
    if fold_rows:
        lines.append("#### Fold-Level Detail (first 10 rows)\n")
        _table_from_rows(lines, fold_rows[:10], exclude={"_mode_tag"})
        if len(fold_rows) > 10:
            lines.append(f"*… {len(fold_rows) - 10} more rows — see per_fold CSV.*")
        lines.append("")


def _render_selector_uplift_per_run(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Selector Uplift (Baseline vs Dynamic)\n")
    csvs = summary.get("csvs") or {}
    rows = csvs.get("selector_comparison") or []
    if rows:
        wanted = ["Pair", "pair", "Sharpe_Baseline", "Sharpe_Dynamic", "Sharpe_Delta",
                  "Return_Delta", "MaxDD_Delta"]
        _table_from_rows(lines, rows, include=wanted, exclude={"_mode_tag"})
    else:
        lines.append("⚠ Selector comparison data not available for this run.")
    lines.append("")


def _render_ablation(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Ablation Summary\n")
    csvs = summary.get("csvs") or {}
    agg_rows = csvs.get("ablation_aggregate") or []
    pair_rows = csvs.get("ablation_per_pair") or []
    if agg_rows:
        lines.append("**Aggregate:**\n")
        _table_from_rows(lines, agg_rows, exclude={"_mode_tag"})
        lines.append("")
    if pair_rows:
        lines.append("**Per Pair:**\n")
        _table_from_rows(lines, pair_rows, exclude={"_mode_tag"})
    if not agg_rows and not pair_rows:
        lines.append("⚠ Ablation data not available.")
    lines.append("")


def _render_vol_guard(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Vol Guard Diagnostics\n")
    csvs = summary.get("csvs") or {}
    rows = csvs.get("vol_guard_summary") or []
    if rows:
        _table_from_rows(lines, rows, exclude={"_mode_tag"})
    else:
        lines.append("⚠ Vol guard diagnostics not available.")
    lines.append("")


def _render_backtest(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Backtest Results\n")
    csvs = summary.get("csvs") or {}
    # Prefer results_summary (v2) then backtest (v1) then log-parsed
    rows = (
        csvs.get("results_summary")
        or csvs.get("results_per_pair")
        or csvs.get("backtest")
    )
    log = summary.get("log") or {}
    if not rows and log.get("backtests"):
        rows = log["backtests"]

    if rows:
        wanted = [
            "Pair", "pair", "Strategy", "Total Return (%)", "Sharpe Ratio",
            "Max Drawdown (%)", "Win Rate (%)", "Profit Factor", "Total Trades",
            "total_return_pct", "sharpe", "max_drawdown_pct", "win_rate_pct", "n_trades",
        ]
        _table_from_rows(lines, rows, include=wanted, exclude={"_mode_tag"})
    else:
        lines.append("⚠ Backtest data not available.")
    lines.append("")


def _render_ml_accuracy(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### In-Sample ML Accuracy\n")
    csvs = summary.get("csvs") or {}
    rows = csvs.get("ml_accuracy")
    log = summary.get("log") or {}
    if not rows and log.get("ml_results"):
        rows = log["ml_results"]

    if rows:
        wanted = ["Model", "model", "Pair", "pair", "Accuracy", "accuracy", "Std", "std",
                  "N Samples", "n_samples"]
        _table_from_rows(lines, rows, include=wanted, exclude={"_mode_tag"})
    else:
        lines.append("⚠ In-sample ML accuracy data not available.")
    lines.append("")


# ---------------------------------------------------------------------------
# Cross-run comparison sections
# ---------------------------------------------------------------------------


def _render_sentiment_comparison(
    lines: list[str], sentiment: dict[str, Any] | None
) -> None:
    lines.append("### Sentiment ON vs OFF (A/C vs B/D)\n")
    if not sentiment:
        lines.append("⚠ Sentiment comparison not computed.")
        lines.append("")
        return
    for w in sentiment.get("warnings") or []:
        lines.append(f"- ⚠ {w}")
    on_ids = ", ".join(sentiment.get("sentiment_on") or []) or "—"
    off_ids = ", ".join(sentiment.get("sentiment_off") or []) or "—"
    lines.append(f"- **Sentiment ON runs:** {on_ids}")
    lines.append(f"- **Sentiment OFF runs:** {off_ids}")
    lines.append(f"- **Valid comparisons:** {', '.join(sentiment.get('valid_comparisons') or []) or '—'}")
    lines.append(f"- **Incomplete comparisons:** {', '.join(sentiment.get('incomplete_comparisons') or []) or '—'}")
    lines.append(f"- **Invalid comparisons:** {', '.join(sentiment.get('invalid_comparisons') or []) or '—'}")
    lines.append("")
    delta_rows = sentiment.get("delta_table") or []
    if delta_rows:
        lines.append("**Delta Table (Sentiment ON − OFF):**\n")
        _table_from_rows(lines, delta_rows)
    else:
        lines.append("⚠ Delta table empty (need both ON and OFF runs).")
    lines.append("")


def _render_gen_comparison(
    lines: list[str], gen: dict[str, Any] | None
) -> None:
    lines.append("### Gen1 vs Gen2 (Missing-Indicator Semantics)\n")
    if not gen:
        lines.append("⚠ Gen1/Gen2 comparison not computed.")
        lines.append("")
        return
    for w in gen.get("warnings") or []:
        lines.append(f"- ⚠ {w}")
    g1_ids = ", ".join(gen.get("gen1") or []) or "—"
    g2_ids = ", ".join(gen.get("gen2") or []) or "—"
    lines.append(f"- **Gen1 runs:** {g1_ids}")
    lines.append(f"- **Gen2 runs:** {g2_ids}")
    lines.append(f"- **Valid comparisons:** {', '.join(gen.get('valid_comparisons') or []) or '—'}")
    lines.append(f"- **Incomplete comparisons:** {', '.join(gen.get('incomplete_comparisons') or []) or '—'}")
    lines.append(f"- **Invalid comparisons:** {', '.join(gen.get('invalid_comparisons') or []) or '—'}")
    lines.append("")
    delta_rows = gen.get("delta_table") or []
    if delta_rows:
        lines.append("**Delta Table (Gen2 − Gen1):**\n")
        _table_from_rows(lines, delta_rows)
    else:
        lines.append("⚠ Delta table empty (need both Gen1 and Gen2 runs).")
    lines.append("")


def _render_selector_aggregate(
    lines: list[str], selector: dict[str, Any] | None
) -> None:
    lines.append("### Selector Uplift Aggregate\n")
    if not selector:
        lines.append("⚠ Selector comparison not computed.")
        lines.append("")
        return
    for w in selector.get("warnings") or []:
        lines.append(f"- ⚠ {w}")
    agg = selector.get("aggregate") or {}
    if agg:
        lines.append("**Mean uplift per pair (Dynamic − Baseline):**\n")
        lines.append("| Pair | Sharpe Δ | Return Δ | MaxDD Δ |")
        lines.append("|------|----------|----------|---------|")
        for pair, metrics in sorted(agg.items()):
            sharpe = _fmt(metrics.get("Sharpe_Delta"))
            ret = _fmt(metrics.get("Return_Delta"))
            dd = _fmt(metrics.get("MaxDD_Delta"))
            lines.append(f"| {pair} | {sharpe} | {ret} | {dd} |")
    else:
        lines.append("⚠ No aggregate selector data available.")
    lines.append("")


def _render_manifest_metadata(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Manifest Metadata\n")
    meta = summary.get("meta") or {}
    md = meta.get("manifest_diagnostics") or {}
    reproducibility = meta.get("reproducibility") or {}
    feature_ordering = meta.get("feature_ordering") or {}
    lines.append(f"- Manifest present: {'yes' if meta.get('manifest_present') else 'no'}")
    lines.append(f"- Legacy mode: {'yes' if meta.get('legacy_mode') else 'no'}")
    lines.append(f"- Canonical manifest path: {md.get('manifest_path') or '—'}")
    lines.append(f"- Canonical manifest run_id: {md.get('manifest_run_id') or '—'}")
    lines.append(f"- Canonical manifest timestamp: {md.get('manifest_timestamp') or '—'}")
    lines.append(f"- Canonical manifest mode tag: {md.get('dl_mode_tag') or '—'}")
    lines.append(f"- Manifest count in run root: {md.get('manifest_count', 0)}")
    if reproducibility:
        lines.append("- Reproducibility seed metadata:")
        lines.append(f"  - experiment_seed: {reproducibility.get('experiment_seed', '—')}")
        lines.append(f"  - numpy_seed: {reproducibility.get('numpy_seed', '—')}")
        lines.append(f"  - python_random_seed: {reproducibility.get('python_random_seed', '—')}")
        lines.append(f"  - torch_seed: {reproducibility.get('torch_seed', '—')}")
    phase_predictor_pairs = sorted((feature_ordering.get("phase_predictor_by_pair") or {}).keys())
    selector_pairs = sorted((feature_ordering.get("strategy_selector_by_pair") or {}).keys())
    if phase_predictor_pairs or selector_pairs:
        lines.append("- Feature ordering metadata:")
        lines.append(f"  - dl_feature_columns: {', '.join(feature_ordering.get('dl_feature_columns') or []) or '—'}")
        lines.append(f"  - phase_predictor_by_pair: {', '.join(phase_predictor_pairs) or '—'}")
        lines.append(f"  - strategy_selector_by_pair: {', '.join(selector_pairs) or '—'}")
    lines.append("")


def _render_parser_diagnostics(lines: list[str], summary: dict[str, Any]) -> None:
    lines.append("### Parser Diagnostics\n")
    meta = summary.get("meta") or {}
    files_found = meta.get("files_found") or []
    lines.append(f"- Recognized CSV files: {len(files_found)}")
    if files_found:
        lines.append(f"- Files: {', '.join(sorted(files_found))}")
    else:
        lines.append("- Files: —")
    lines.append(f"- Log parsed: {'yes' if summary.get('log') else 'no'}")
    lines.append("")


def _render_integrity_section(
    lines: list[str],
    title: str,
    section: dict[str, Any] | None,
) -> None:
    lines.append(f"### {title}\n")
    if not section:
        lines.append("- No diagnostics.")
        lines.append("")
        return
    errors = section.get("errors") or []
    warnings = section.get("warnings") or []
    lines.append(f"- Errors: {len(errors)}")
    lines.append(f"- Warnings: {len(warnings)}")
    for err in errors:
        lines.append(f"  - ❌ {err}")
    for warning in warnings:
        lines.append(f"  - ⚠ {warning}")
    lines.append("")


# ---------------------------------------------------------------------------
# Table helper
# ---------------------------------------------------------------------------


def _table_from_rows(
    lines: list[str],
    rows: list[dict[str, Any]],
    include: list[str] | None = None,
    exclude: set[str] | None = None,
) -> None:
    """Render *rows* as a markdown table appended to *lines*."""
    if not rows:
        lines.append("*(empty)*")
        return

    exclude = exclude or set()
    all_cols = list(rows[0].keys())

    if include:
        # Keep only columns that exist in the data and are in the include list
        cols = [c for c in include if c in all_cols]
        # If none matched, fall back to all
        if not cols:
            cols = [c for c in all_cols if c not in exclude]
    else:
        cols = [c for c in all_cols if c not in exclude]

    if not cols:
        lines.append("*(no columns)*")
        return

    header = "| " + " | ".join(str(c) for c in cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    lines.append(header)
    lines.append(sep)
    for row in rows:
        cell = " | ".join(_fmt(row.get(c)) for c in cols)
        lines.append(f"| {cell} |")


def _fmt(val: Any) -> str:
    """Format a value for markdown table display."""
    if val is None:
        return "—"
    if isinstance(val, float):
        return f"{val:.4f}"
    return str(val)
